# Generated by Django 5.1.1 on 2025-02-11 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deadline', models.DateTimeField()),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('complited', 'Complited')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complited_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_orders', to='users.customer')),
            ],
        ),
        migrations.CreateModel(
            name='AcceptedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.freelancer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_order', to='orders.order')),
            ],
        ),
    ]
