# Generated by Django 5.1.1 on 2024-10-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deadline', models.DateTimeField()),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('complited', 'Complited')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complited_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
